### ISSUE TITLE
styles.css a bit too generic and could interfere with other login page behaviour

### ISSUE THREAD

**Issue by danmarsden** [bdecentgmbh/moodle-auth_magic#3]
https://github.com/bdecentgmbh/moodle-auth_magic/blob/dev/styles.css#L1

you should be more specific there so it's only targeting auth_magic content and not other content that might end up using a btn-block  class name.

**Comment by stefanscholz** [comment]
Due to the separation of the repositories, we do no longer need css for the free version at all.

Closing the issue.
