### ISSUE TITLE
invalid hand-rolled install.xml file.

### ISSUE THREAD

**Issue by danmarsden** [bdecentgmbh/moodle-auth_magic#4]
The install.xml has been handwritten.

This needs to be fixed using the Moodle xmldb editor (under admin > development > XMLDB.)

Please hit the "load" link for your plugin install.xml file in the moodle xmldb editor, and then make Moodle think there is an update to the file (easiest way to do this is to change the description of a table - add a full stop or something similar.) Then get XMLDB to "Save" the updated file which will remove all the old invalid xml from your file.

not a blocker for approval, but will clean the file up a bit.

**Comment by stefanscholz** [comment]
The install.xml has been cleaned up 
https://github.com/bdecentgmbh/moodle-auth_magic/commit/ebe67b13be2bc5e93906b1a6a3d95aeb3ea658c7#diff-4013433adb48858dfeac13caf181742020b6c693bc853298312c45b134377cb6

@danmarsden please close the issue if you are happy with the result.

**Comment by danmarsden** [comment]
@stefanscholz I don't take another look at plugins unless going through the review process again - feel free to close any issues when you've sorted them and when you're ready for another review please upload the updated code to the plugins db entry and hit the "Request re-approval" button on the developer zone tab - thanks!

**Comment by stefanscholz** [comment]
Hi @danmarsden, sure, that's clear! I was about to actually request that yesterday but unfortunately ran out of time writing responses for Brendan's and your feedback.
